# # #

FROM nginx:alpine

WORKDIR /app

# # #
# Copy the nginx configuration file.

COPY config/nginx.conf /etc/nginx/nginx.conf

# # #
# Make the container run the nginx server and reload it every 6 hours.

CMD ["/bin/sh", "-c", "while :; do sleep 6h & wait ${!}; nginx -s reload; done & nginx -g 'daemon off;'"]