/**
 * Public data repository types and PostgreSQL implementation.
 *
 * - `PublicDataRepository`: Interface for API-ready data access.
 * - `PostgresPublicDataRepository`: Concrete implementation using PostgreSQL and `pg` pool.
 *
 * Responsibilities:
 *   - Managing connection pool lifecycle (`close`).
 *   - Streaming downloads as PostgreSQL COPY output.
 *   - Providing available data listings.
 *   - Handling health checks (`ping`).
 */

import type { Readable } from 'node:stream';
import type { Pool, PoolClient, QueryResultRow } from 'pg';
import { to as copyTo } from 'pg-copy-streams';

import type { AgencyId, availableRow, DownloadFilters } from '../api/consts.js';
import {
  buildAvailableRoutesSql,
  buildAvailableSql,
  buildAvailableTripsSql,
  buildApiGeneralCopySql,
  type DatabaseIdentifiers,
} from './sql.js';

/**
 * Repository interface for fetching, listing, and streaming API data.
 * 
 * Exposes a minimal contract for backends powering the public API.
 */
export interface PublicDataRepository {
  /**
   * Close the underlying database pool and release all resources.
   */
  close(): Promise<void>;

  /**
   * Stream a filtered dataset as CSV using PostgreSQL COPY.
   * 
   * @param filters Download query filters.
   * @returns Node Readable stream with CSV data.
   */
  createApiGeneralDownload(filters: DownloadFilters): Promise<Readable>;

  /**
   * List all available data groupings for API "available" response.
   * 
   * @returns Rows each representing a (month, agency, reference) grouping.
   */
  listAvailable(): Promise<readonly availableRow[]>;

  /** List all distinct non-null route IDs. */
  listAvailableRoutes(agencyId?: AgencyId): Promise<readonly string[]>;

  /** List all distinct non-null trip IDs. */
  listAvailableTrips(agencyId?: AgencyId): Promise<readonly string[]>;

  /**
   * Ping the database for liveness (throws if unreachable).
   */
  ping(): Promise<void>;
}

/** Internal row type for Postgres listing. */
interface DatabaseAvailableRow extends QueryResultRow, availableRow {}

interface DatabaseAvailableValueRow extends QueryResultRow {
  readonly value: string;
}

/**
 * Concrete Postgres implementation for the public data repository.
 * 
 * Handles streaming and querying, ensuring proper client release.
 */
export class PostgresPublicDataRepository implements PublicDataRepository {
  /**
   * @param pool         PostgreSQL connection pool.
   * @param identifiers  Table/column configuration.
   */
  constructor(
    private readonly pool: Pool,
    private readonly identifiers: DatabaseIdentifiers,
  ) {}

  /**
   * Flushes all active queries and disposes of the pool.
   */
  async close(): Promise<void> {
    await this.pool.end();
  }

  /**
   * Returns a readable stream serving filtered general data as CSV (COPY).
   * 
   * The caller is responsible for consuming and closing the stream.
   */
  async createApiGeneralDownload(filters: DownloadFilters): Promise<Readable> {
    const sql = buildApiGeneralCopySql(filters, this.identifiers);
    return this.createCopyStream(sql);
  }

  /**
   * Lists all available data rows for endpoint grouping/caching.
   *
   * Each row contains yearmonth, agency_id, and reference.
   */
  async listAvailable(): Promise<readonly availableRow[]> {
    const sql = buildAvailableSql(this.identifiers);
    const result = await this.pool.query<DatabaseAvailableRow>(sql);
    return result.rows;
  }

  async listAvailableRoutes(agencyId?: AgencyId): Promise<readonly string[]> {
    return this.listAvailableValues(
      buildAvailableRoutesSql(this.identifiers, agencyId),
    );
  }

  async listAvailableTrips(agencyId?: AgencyId): Promise<readonly string[]> {
    return this.listAvailableValues(
      buildAvailableTripsSql(this.identifiers, agencyId),
    );
  }

  /**
   * Simple health check.
   * Throws if the database cannot be contacted.
   */
  async ping(): Promise<void> {
    await this.pool.query('SELECT 1');
  }

  private async listAvailableValues(sql: string): Promise<readonly string[]> {
    const result = await this.pool.query<DatabaseAvailableValueRow>(sql);
    return result.rows.map((row) => row.value);
  }

  /**
   * Opens a COPY TO STDOUT stream using the given SQL statement.
   * 
   * Ensures that the database client is safely released when streaming is done (or errors).
   * 
   * @param sql SQL statement (preferably generated by `buildApiGeneralCopySql`).
   * @returns Node Readable stream to pipe/download results.
   * @throws Error if client allocation or streaming setup fails.
   */
  private async createCopyStream(sql: string): Promise<Readable> {
    const client = await this.pool.connect();

    try {
      const stream = client.query(copyTo(sql));
      this.releaseClientWhenFinished(client, stream);
      return stream;
    } catch (error) {
      // Release the client if COPY setup fails
      client.release(error instanceof Error ? error : true);
      throw error;
    }
  }

  /**
   * Installs listeners on the provided stream to ensure the DB client is released exactly once.
   * 
   * Listens for 'end', 'close', and 'error' events; releases the client accordingly.
   * 
   * @param client Acquired PoolClient to release on stream completion.
   * @param stream Readable stream to observe (from client.query).
   */
  private releaseClientWhenFinished(client: PoolClient, stream: Readable): void {
    let released = false;

    const release = (error?: Error): void => {
      if (!released) {
        released = true;
        client.release(error);
      }
    };

    stream.once('end', () => release());
    stream.once('close', () => release());
    stream.once('error', (err: Error) => release(err));
  }
}
