# # #

name: deploy-emds

services:

  nginx:
    image: ghcr.io/carrismetropolitana/deploy-emds-nginx:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 6191:80
    depends_on:
      api:
        condition: service_healthy

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  api:
    image: ghcr.io/carrismetropolitana/deploy-emds-api:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env
    environment:
      HOST: 0.0.0.0
      NODE_ENV: production
      PORT: 6192
