name: Build & Publish Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:

  nginx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push nginx image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/nginx/Dockerfile
          push: true
          cache-from: type=gha,scope=nginx
          cache-to: type=gha,mode=max,scope=nginx
          tags: |
            ghcr.io/carrismetropolitana/deploy-emds-nginx:latest
            ghcr.io/carrismetropolitana/deploy-emds-nginx:${{ github.sha }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/server/Dockerfile
          push: true
          cache-from: type=gha,scope=server
          cache-to: type=gha,mode=max,scope=server
          tags: |
            ghcr.io/carrismetropolitana/deploy-emds-server:latest
            ghcr.io/carrismetropolitana/deploy-emds-server:${{ github.sha }}
